### PR TITLE
Jayson's Group added a Gacha System code

### PR DESCRIPTION
**Pull request by JaysM32**
Group member: 
1. Jayson M 
2. Bernard W
3. Leon J
4. Eric LK

### CODE REVIEW

**Comment by raveltan** [comment]
@JaysM32 

You're still using a lot of global variable in your code,

Try to remove them and instead pass the data to a function and then return the result.

I'll merge the request after you had finish the changes

**Comment by raveltan** [comment]
@JaysM32 

Also try to change the naming scheme
from something like:
FirstData

to a standard python naming scheme,
first_data

**Comment by JaysM32** [comment]
updates have been made, ko

**Comment by raveltan** [comment]
Great Job Guys!

**Pull request merged**
