### PR TITLE
Moved Directory

### PR DESCRIPTION
**Pull request by FabioSebs**

### CODE REVIEW

**Comment by raveltan** [comment]
Great Job Fabio!

**Comment by FabioSebs** [comment]
Thank you ko Ravel! 🙏🏼

**Comment by raveltan** [comment]
@FabioSebs 

Here are some suggestions for you:
1. Try to use # to mark a single line and multi line comment, """ is usually used to create a docstring comment (this is not a rule, but just best practices)
2. Try not to put your functions on the middle of your code, it will be cleaner if you can put them either on the top or bottom part.

**Comment by FabioSebs** [comment]
Thank you ko Ravel I will keep that in mind next time I code Python to make
it more readable.

**Pull request merged**
